repos:
  - name: repo-1
    title: Repository 1
    image: favicon.png
    url: https://github.com/A-Baji/mk-docs-sample1.git
    branch: master
  - name: repo-2
    title: Repository 2
    image: favicon.png
    url: https://github.com/A-Baji/mk-docs-sample2.git
    branch: master
  - name: repo-3
    title: Repository 3
    image: favicon.png
    url: https://github.com/A-Baji/mk-docs-sample3.git
    branch: master
element_id: multirepo
target_dir: docs
repos_dir: docs_src
index_tpl: index.tpl
extra_files:
    - styles.css