repos:
  - name: repo-1
    title: My Repository 1
    image: icon-repo-1.png
    url: https://github.com/A-Baji/mk-docs-sample1.git
    branch: master
  - name: repo-2
    title: My Repository 2
    image: icon-repo-1.png
    url: https://github.com/A-Baji/mk-docs-sample2.git
    branch: master
  - name: repo-3
    title: My Repository 3
    image: icon-repo-1.png
    url: https://github.com/A-Baji/mk-docs-sample3.git
    branch: master
element_id: multirepo
target_dir: docs
repos_dir: src
index_tpl: index.tpl
# extra_files:
#     - styles.css
#     - images/search.svg